-- Migration: extend sys_menus for vben v5 meta fields
-- Note: adjust SQL types for your DB (MySQL assumed)
CREATE TABLE `sys_menus` (
  `id` varchar(64) NOT NULL,
  `pid` varchar(64) NOT NULL DEFAULT '' COMMENT '父级ID(根为空字符串)',
  `level` tinyint(2) NOT NULL DEFAULT '0' COMMENT '层级深度 根=0',
  `name` varchar(64) NOT NULL DEFAULT '' COMMENT '路由名称(routeName，全局唯一)',
  `title` varchar(128) NOT NULL DEFAULT '' COMMENT '菜单/页面标题',
  `icon` varchar(128) NOT NULL DEFAULT '' COMMENT '图标',
  `active_icon` varchar(128) NOT NULL DEFAULT '' COMMENT '激活图标',
  `keep_alive` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否缓存',
  `hide_in_menu` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否在菜单隐藏',
  `hide_in_tab` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否在标签页隐藏',
  `hide_in_breadcrumb` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否在面包屑隐藏',
  `hide_children_in_menu` tinyint(1) NOT NULL DEFAULT '0' COMMENT '子级是否在菜单隐藏',
  `authority` json DEFAULT NULL COMMENT '权限数组(JSON)',
  `permission` varchar(128) NOT NULL DEFAULT '' COMMENT '主权限编码（单值/按钮用）',
  `badge` varchar(64) NOT NULL DEFAULT '' COMMENT '徽标文本',
  `badge_type` varchar(16) NOT NULL DEFAULT 'normal' COMMENT '徽标类型 dot|normal',
  `badge_variants` varchar(32) NOT NULL DEFAULT 'success' COMMENT '徽标样式',
  `full_path_key` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'tab key 使用完整路径',
  `active_path` varchar(255) NOT NULL DEFAULT '' COMMENT '激活菜单路径',
  `affix_tab` tinyint(1) NOT NULL DEFAULT '0' COMMENT '固定标签',
  `affix_tab_order` int(11) NOT NULL DEFAULT '0' COMMENT '固定标签排序',
  `iframe_src` varchar(255) NOT NULL DEFAULT '' COMMENT 'iframe地址',
  `ignore_access` tinyint(1) NOT NULL DEFAULT '0' COMMENT '忽略权限校验',
  `link` varchar(255) NOT NULL DEFAULT '' COMMENT '外链地址(新窗口)',
  `max_num_of_open_tab` int(11) NOT NULL DEFAULT '-1' COMMENT '同名最大标签数',
  `menu_visible_with_forbidden` tinyint(1) NOT NULL DEFAULT '0' COMMENT '可见但403',
  `open_in_new_window` tinyint(1) NOT NULL DEFAULT '0' COMMENT '新窗口打开',
  `order_no` int(11) NOT NULL DEFAULT '0' COMMENT '显示排序(一级)',
  `query_params` json DEFAULT NULL COMMENT '菜单参数(JSON)',
  `no_basic_layout` tinyint(1) NOT NULL DEFAULT '0' COMMENT '不使用基础布局',
  `path` varchar(255) NOT NULL DEFAULT '' COMMENT '路由地址(相对)',
  `full_path` varchar(512) NOT NULL DEFAULT '' COMMENT '冗余完整路径',
  `redirect` varchar(255) NOT NULL DEFAULT '' COMMENT '重定向地址',
  `component` varchar(255) NOT NULL DEFAULT '' COMMENT '组件路径',
  `bind_api` tinyint(1) NOT NULL DEFAULT '0' COMMENT '绑定数据权限 1是 0否',
  `created_at` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建时间(时间戳秒/毫秒统一)',
  `updated_at` bigint(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态 1启用 0禁用',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '1' COMMENT '软删除 1正常 -1删除',
  `type` tinyint(1) NOT NULL DEFAULT '2' COMMENT '1目录 2菜单 3按钮',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_name` (`name`),
  UNIQUE KEY `uk_pid_path` (`pid`,`path`),
  KEY `idx_type_status` (`type`,`status`),
  KEY `idx_pid_order` (`pid`,`order_no`),
  KEY `idx_type_permission` (`type`,`permission`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;